### ISSUE TITLE
Needs a new Logo

### ISSUE THREAD

**Issue by Mystro256** [Mystro256/Not64#1]
A new logo should be made for not64, rather than the current one:

https://raw.githubusercontent.com/Mystro256/Not64/a9264b10a0983e3380a309d7db63b1633fd5578e/release/apps/not64/icon.png

**Comment by MelonSpeedruns** [comment]
I could actually do that for you... I'm on it.

**Comment by MelonSpeedruns** [comment]
Good enough? : http://imgur.com/Sdd2Ati

**Comment by Mystro256** [comment]
Thanks! Fixed in last commit.
